# Generated by Django 6.0.2 on 2026-04-05 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('unite_mesure', models.CharField(blank=True, default='', max_length=20)),
                ('tolerance_min', models.FloatField(blank=True, null=True)),
                ('tolerance_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Composants',
            },
        ),
        migrations.CreateModel(
            name='Systeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Systèmes',
            },
        ),
        migrations.CreateModel(
            name='TypeFiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Types de fiches',
            },
        ),
        migrations.CreateModel(
            name='FicheSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commentaire_global', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='fiches_pdf/')),
                ('intervenant_nom', models.CharField(blank=True, max_length=100)),
                ('intervenant_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('date_signature', models.DateTimeField(auto_now_add=True)),
                ('controleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type_fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to='maintenance.typefiche')),
            ],
        ),
        migrations.CreateModel(
            name='AvisFiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='maintenance.fichesuivi')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('marque', models.CharField(max_length=100)),
                ('niveau_carburant', models.CharField(blank=True, max_length=50)),
                ('niveau_huile', models.CharField(blank=True, max_length=50)),
                ('niveau_eau', models.CharField(blank=True, max_length=50)),
                ('heure_fonctionnement', models.CharField(blank=True, max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('controleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneFicheSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_mesuree', models.FloatField()),
                ('observation', models.TextField(blank=True)),
                ('conforme', models.BooleanField(default=True)),
                ('date_mesure', models.DateTimeField(auto_now_add=True)),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.composant')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_suivi', to='maintenance.fichesuivi')),
            ],
            options={
                'verbose_name_plural': 'Lignes fiches suivi',
            },
        ),
        migrations.CreateModel(
            name='LigneHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement', models.CharField(max_length=150)),
                ('symptomes', models.TextField()),
                ('travaux', models.TextField()),
                ('methode_entretien', models.CharField(choices=[('depannage', 'Dépannage'), ('reparation', 'Réparation'), ('entretien_conduite', 'Entretien de conduite'), ('entretien_preventif', 'Entretien préventif conditionnel'), ('entretien_systematique', 'Entretien systématique'), ('amelioration', 'Amélioration')], max_length=30)),
                ('observations', models.TextField(blank=True)),
                ('outillage_pieces', models.TextField(blank=True, verbose_name='Outillages / pièces')),
                ('historique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='maintenance.historiquepanne')),
            ],
        ),
        migrations.AddField(
            model_name='composant',
            name='systeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='maintenance.systeme'),
        ),
        migrations.AddField(
            model_name='systeme',
            name='type_fiche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systemes', to='maintenance.typefiche'),
        ),
        migrations.CreateModel(
            name='EvaluationComposant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('BON', 'BON'), ('PASSABLE', 'PASSABLE'), ('MAUVAIS', 'MAUVAIS')], max_length=10)),
                ('decision', models.CharField(choices=[('REPARER', 'Réparer'), ('NE_PAS_REPARER', 'Ne pas réparer')], max_length=15)),
                ('remarque', models.TextField(blank=True)),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.composant')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='maintenance.fichesuivi')),
            ],
            options={
                'verbose_name_plural': 'Évaluations composants',
                'unique_together': {('fiche', 'composant')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='composant',
            unique_together={('systeme', 'nom')},
        ),
    ]
